/**
 * Fax.to REST API client for Scala
 * This is Fax.to REST API client for Scala.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class InlineResponse2003History (
  id: Option[Integer] = None,
  created: Option[InlineResponse2003Created] = None,
  documentId: Option[Integer] = None,
  document: Option[String] = None,
  recipient: Option[String] = None,
  // The status of the fax job
  status: Option[String] = None
)

