/**
 * Fax.to REST API client for Scala
 * This is Fax.to REST API client for Scala.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class InlineResponse2004MetaPagination (
  total: Option[Integer] = None,
  count: Option[Integer] = None,
  perPage: Option[Integer] = None,
  currentPage: Option[Integer] = None,
  totalPages: Option[Integer] = None,
  links: Option[InlineResponse2004MetaPaginationLinks] = None
)

