/**
 * Fax.to REST API client for Scala
 * This is Fax.to REST API client for Scala.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

import java.util.Date

case class InlineResponse20017Numbers (
  id: Option[Integer] = None,
  orderReference: Option[String] = None,
  countryCode: Option[String] = None,
  country: Option[String] = None,
  cityName: Option[String] = None,
  areaCode: Option[String] = None,
  didGroupId: Option[Integer] = None,
  didNumber: Option[String] = None,
  expirationDate: Option[Date] = None,
  status: Option[String] = None
)

