/**
 * Fax.to REST API client for Scala
 * This is Fax.to REST API client for Scala.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

import java.util.Date

case class InlineResponse2008Files (
  id: Option[Integer] = None,
  filename: Option[String] = None,
  pages: Option[Integer] = None,
  size: Option[Integer] = None,
  uploaded: Option[Date] = None
)

