/**
 * Fax.to REST API client for Scala
 * This is Fax.to REST API client for Scala.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model

import java.util.Date

case class InlineResponse2009 (
  status: Option[String] = None,
  userId: Option[Integer] = None,
  createdDate: Option[Date] = None,
  id: Option[Integer] = None,
  filename: Option[String] = None,
  origFilename: Option[String] = None,
  previewFile: Option[String] = None,
  previewImage: Option[String] = None,
  previewInStorage: Option[Integer] = None,
  fileExtension: Option[String] = None,
  filenameUploaded: Option[String] = None,
  filesize: Option[String] = None,
  s3: Option[Integer] = None,
  serverDocumentId: Option[Integer] = None,
  teamUserId: Option[Integer] = None,
  totalPages: Option[Integer] = None,
  updatedAt: Option[Date] = None
)

